#!/bin/bash

# Read input roles
ROLE_1="viewer"
ROLE_2="editor"

# Generate role.yml
cat <<EOF > role.yml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: $ROLE_1
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: $ROLE_2
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["get", "watch", "list", "create", "update", "delete"]
EOF
